# Site settings
baseurl = "http://watercommonsindex.org/"
languageCode = "en-us"
title = " Water Commons Index"
theme = "hugo-agency-theme"
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$", "_old"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Your name"
  description = "Your description"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Water Commons Index"
    # Optional logo as brand stored in img/
    logo = "logo.svg"
    services = "Apps"
    portfolio = "Practices"
    about = "About"
    team = "Team"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Let's manage our water commons!"
    subtitle = "Smart Water Decisions"
    buttonText = "Tell me more"


  # Services section
  [params.services]
    enable = true
    title = "Applications"
    subtitle = "These applications provide a regional city planner view of where water recharge could be best incentivized (Recharge Index), and then a landscape designer perspective of which practices could provide the most benefit given the context of the given parcel (Permeable Practices Index)."

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-bolt"
      title = "Recharge Index"
      description = "[![](img/app_recharge-index_map-diagram.png)](http://eemsonline.org/?PROJECT=Water%20Commons&Author=Dustin%20Pearce)<br>Evaluate parcels within the watershed based on impervious surface, soil properties, and aquifer location. Status: Beta."
      url = "http://eemsonline.org/?PROJECT=Water%20Commons&Author=Dustin%20Pearce"

    [[params.services.row.list]]
      icon = "fa-tint"
      title = "Permeable Practices Index"
      description = "[![](img/app_permeable-practices.png)](https://ecoquants.shinyapps.io/wci-micro-app/)<br>Based on the context of a given parcel from the Recharge Index, various permeable practices are suggested. Status: Pre-alpha."
      url = "https://ecoquants.shinyapps.io/wci-micro-app/"

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Permeable Practices"
    subtitle = "Strategic practices to increase value to the Water Commons."

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close practice"


    # About section
  [params.about]
    enable = false
    title = "About"
    subtitle = "Lorem ipsum dolor sit amet consectetur."
    endpoint = "Be part<br>of our<br>story!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = "2009-2011"
      title = "Our Humble Beginnings"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "2.jpg"
      date = "March 2011"
      title = "An Agency is Born"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "3.jpg"
      date = "December 2012"
      title = "Our Humble Beginnings"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "4.jpg"
      date = "July 2014"
      title = "Phase Two Expansion"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Our team"
    subtitle = "The Water Commons Alliance is a small multi-disciplinary group of designers and scientists interested in developing data-driven tools for enhancing California’s water supply."
    #description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "matt-gries.png"
      name = "Matt Gries (AIA)"
      position = "Architect"
      #reportsTo = "CTO"
      livesIn = "Santa Barbara, CA"
      #scope = [
      #  "UX for [member dashboard](#)",
      #  "Maintainer for [awesome-project](#)",
      #  "Open Source [community management](#)"
      #]
      # For bio markdown and even multiline strings are available.
      bio = """Matt Gries AIA is a licensed Architect ([DesignARC](http://www.designarc.net/)), member of the [Community Environmental Council](http://www.cecsb.org/) Partnership Council, and co-founder of the Water Commons Alliance. For over 15 years, Matt has focused on resource, climatology and sustainability issues that are inherently tied to the design process, with a particular passion for solving problems related to water management. Matt is now working with the AIA Santa Barbara in order to promote a bottom-up approach to architecture and landscape design that is more deeply integrated with Santa Barbara’s complex water scenario."""
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "meg-west.jpg"
      name = "Meg West (LEED AP)"
      livesIn = "Ashland, OR"
      position = "Landscape Designer"
      bio = """Meg West is the principal Landscape Architect at [Meg West Design](http://www.megwestdesign.com). She was inspired to run for a seat on the [Goleta Water District Board of Directors](http://www.goletawater.com/about-the-district/board-of-directors) in 2014 after serving on the Goleta Planning Commission for four years.  Steering the Goleta Water District towards more sustainable long-term water supply during this drought has deepened her understanding of water issues dramatically. She is now the Vice President of the Board and is active in local and statewide efforts to promote and implement integrated solutions for water supply, soil health, pollution, and climate."""
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "ben-best.jpg"
      name = "Ben Best (PhD)"
      livesIn = "Santa Barbara, CA"
      position = "Environmental Data Scientist"
      bio = """Ben Best is an environmental data scientist with a background in marine spatial ecology. Through his newly formed [EcoQuants](http://ecoquants.com/) consultancy, he is working with NASA, NOAA, National Renewable Lab and the National Park Service. He has taught a variety of graduate courses at UC Santa Barbara: GIS, Advanced GIS, Environmental Informatics, Landscape Ecology and Conservation Planning. He was the senior analyst for the Ocean Health Index and completed a PhD at Duke University in the Marine Geospatial Ecology Lab."""
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]
      
    [[params.team.members]]
      img = "dustin-pearce.jpg"
      name = "Dustin Pearce (MESM)"
      livesIn = "Santa Barbara, CA"
      position = "GIS Analyst"
      bio = """Dustin Pearce joined the [Conservation Biology Institute](https://consbio.org/) in December of 2015. His background in geospatial sciences has focused on the interplay of working agricultural lands, natural lands, and renewable energy development in California. Growing up in the San Joaquin Valley, his connection with agricultural and working lands initiated his interest in biology. Dustin holds a M.E.S.M. in Economics and Politics of the Environment from the Bren School of Environmental Science & Management, and a B.S. in Conservation Biology from Arizona State University. His work with the Conservation Biology Institute is focused on stakeholder engagement and smart planning for renewable energy development and environmental protection throughout California."""
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

  # Client section
    [params.clients_list]
      enable = false
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "envato.jpg"
        link = "#"

      [[params.clients]]
        logo = "designmodo.jpg"
        link = "#"

      [[params.clients]]
        logo = "themeforest.jpg"
        link = "#"

      [[params.clients]]
        logo = "creative-market.jpg"
        link = "#"

  # Contact section
  [params.contact]
    enable = true
    title = "Contact us"
    #subtitle  = "Lorem ipsum dolor sit amet consectetur."
    buttonText = "Send message"
    # netlify = true

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"
    email = "ben@ecoquants.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    [params.contact.captcha]
    # https://www.google.com/recaptcha
    sitekey = "6LfbCnYUAAAAAIcA4nbcLl25rViUVeqHz_G2VWqe"

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "#"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "#"
      title = "Facebook"

    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "#"
      title = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
